import services from '@/lib/services'
import Navbar from './components/Navbar/Navbar'
import 'swiper/css';
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/autoplay'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const categories: ICategory[] = await services.cate.getCates()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar categories={categories} />
        <div className='mt-[50px]'>
          {children}
        </div>
      </body>
    </html>
  )
}
